// Package netplan writes the ONE netplan file this tool owns:
// /etc/netplan/90-mseg-tester.yaml. It is always a full, wholesale
// rewrite -- there is no incremental "add this VLAN, remove that one"
// step, because netplan itself doesn't work that way: on `netplan apply`
// (or, here, on the next boot), whatever's NOT declared in the merged
// config across all netplan files simply isn't (re)created. Writing a
// fresh file naming only the one target segment's VLAN is what "disable
// the others" actually means in practice -- there's nothing else to
// explicitly tear down.
//
// Most segments ride as an 802.1Q-tagged VLAN sub-interface on top of the
// trunk NIC (Proxmox hands this VM one NIC, trunked with every segment's
// VLAN tag, set up once by hand -- see the cloud-init/README notes on
// that one-time step). One segment, though, may instead be the trunk
// port's NATIVE/untagged VLAN -- see IfaceName below.
package netplan

import (
	"fmt"
	"os"
)

const path = "/etc/netplan/90-mseg-tester.yaml"

// IfaceName returns the interface Write configures (and the same one
// internal/checks looks addresses up on) for segment, given which
// segment (if any) is the trunk's native/untagged one. A tagged segment
// gets its own VLAN sub-interface, "<trunkInterface>.<segment>"; the
// native segment (when segment == nativeSegment and nativeSegment != "")
// IS the trunk interface itself -- there's no ".segment" sub-interface
// for it at all, since its traffic never carries an 802.1Q tag.
func IfaceName(trunkInterface, segment, nativeSegment string) string {
	if nativeSegment != "" && segment == nativeSegment {
		return trunkInterface
	}
	return fmt.Sprintf("%s.%s", trunkInterface, segment)
}

// Write generates and installs the netplan config for exactly one active
// segment. Does NOT call `netplan apply` -- this tool's whole model is
// "write config, then reboot" (see cmd/mseg-tester's run loop), so a live
// apply here would just be redundant work before the reboot throws it
// away and re-derives the same state from disk anyway.
func Write(trunkInterface, segment, nativeSegment string) error {
	var content string
	if nativeSegment != "" && segment == nativeSegment {
		// The active segment IS the trunk's native/untagged VLAN --
		// configure the trunk interface directly. No vlans stanza at
		// all: there's nothing 802.1Q about this segment's traffic.
		content = fmt.Sprintf(`# Generated by mseg-tester -- do not hand-edit, it is overwritten
# wholesale every time the active segment changes. See internal/netplan.
#
# Segment %s is this trunk's NATIVE/untagged VLAN -- its traffic arrives
# directly on %s, not on a tagged sub-interface, so %s is configured here
# exactly as any normal single-segment NIC would be.
#
# dhcp6 stays false -- this network uses SLAAC (router advertisements),
# not DHCPv6. accept-ra/link-local are set explicitly rather than left to
# netplan's defaults: OVN on this network can only ever deliver a
# SOLICITED router advertisement (its own periodic RA is unconditionally
# dropped -- see internal/checks' package doc), so a client MUST have a
# link-local address to source its router solicitation from, or SLAAC
# never completes at all. link-local: [] has broken this before.
network:
  version: 2
  ethernets:
    %s:
      dhcp4: true
      dhcp6: false
      accept-ra: true
      link-local: [ipv4, ipv6]
`, segment, trunkInterface, trunkInterface, trunkInterface)
	} else {
		ifaceName := IfaceName(trunkInterface, segment, nativeSegment)
		vlanID := segment // ovn-fabric's own convention too: the segment name IS the VLAN ID

		content = fmt.Sprintf(`# Generated by mseg-tester -- do not hand-edit, it is overwritten
# wholesale every time the active segment changes. See internal/netplan.
#
# The trunk interface itself carries no address of its own here -- it
# exists purely so the tagged VLAN sub-interface below can ride on top of
# it. "optional: true" tells systemd-networkd-wait-online not to block
# boot waiting for IT specifically to become "routable" (it never will,
# it's a pure VLAN carrier) -- without this, boot can hang for a long
# time (observed: "no limit" on systemd-networkd-wait-online.service)
# waiting on an interface that was never going to get an address.
#
# dhcp6 stays false -- this network uses SLAAC (router advertisements),
# not DHCPv6. accept-ra/link-local are set explicitly rather than left to
# netplan's defaults: OVN on this network can only ever deliver a
# SOLICITED router advertisement (its own periodic RA is unconditionally
# dropped -- see internal/checks' package doc), so a client MUST have a
# link-local address to source its router solicitation from, or SLAAC
# never completes at all. link-local: [] has broken this before.
network:
  version: 2
  ethernets:
    %s:
      dhcp4: false
      dhcp6: false
      optional: true
  vlans:
    %s:
      id: %s
      link: %s
      dhcp4: true
      dhcp6: false
      accept-ra: true
      link-local: [ipv4, ipv6]
`, trunkInterface, ifaceName, vlanID, trunkInterface)
	}

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o600); err != nil {
		return fmt.Errorf("netplan: writing %s: %w", tmp, err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("netplan: renaming %s -> %s: %w", tmp, path, err)
	}
	return nil
}
